### ISSUE TITLE
Non-admin user unable to see broken links in report

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe-labs/silverstripe-externallinks#73] opened 2021-09-05 21:02 UTC
## Overview
Non admin user in group with all permissions ticket (except full admin access) was unable to see the broken link in the report.  Admin user was able to see the broken link record.

## Steps to replicate
0. Given I have a CMS user in group with all permissions ticket (except full admin access)
1. Given I have a page called "Page with broken links"
2. And I click Link to external URL and I fill in the URL field with http://fsdjoifidsohfiohfsoifhiodshfhdosi.com, and I publish the page
3. When I go to the Reports administration section
4. And I click External broken links report
5. And I click Create new report
6. **Expected:** Then I should see "Page with broken links" in the report
7. **Actual result:** I do not see "Page with broken links" in the report

## Acceptance
- [x] Any Member that has access the `CMS_ACCESS_CMS_Main` has access to the broken links report

##PR's
- silverstripe/silverstripe-externallinks#78

**Comment by sabina-talipova** [comment] 2022-04-26 00:49
I couldn't reproduce this issue in my environment by following "Steps to replicate". All users who have an access to the 'Reports' section will see a list of pages with broken links. 
There is one possible case, when user won't be able to see some pages in the list. If page itself has additional restriction for view and user doesn't have "Content permissions -> View any page".
@brynwhyman, could you provide more detail about permissions to access "Page with broken links" page and list of User permissions.
Not sure, should we show page in the list, if page's author explicitly restricts access to view page.

**Comment by sabina-talipova** [comment] 2022-04-26 01:09
Probably, accessible solution is show full list of pages with broken links, but for pages with restriction, we won't provide link to the page. So in this case, use will see all pages with broken links, but have access to view or edit page only if he has a permission. 

To achieve this we should make the following changes. 

In the method `FieldHolder(...)` in `GridField` class, where we check that `$record` (in our case -> Page) has method `canView()` and it returns false, add additional checking for `$this->name`, and only if it is not 'Report' skip other steps.

```php
 if ($record->hasMethod('canView') && !$record->canView() **&& $this->name != 'Report'**) {
     continue;
  } 
```
We need this to populate GridFields with data in Reports even if user doesn't canView().

In method `formatValue()` in `GridFieldDataColumns` class, where we run closures function for formatting records we should replace 
```php
return $spec($value, $item);
```

to 
```php
 return ($item->hasMethod('canView') && !$item->canView() && $gridField->name === 'Report')
               ? $spec($value, $item, true)
                : $spec($value, $item, false); 
```

That change provides some kind of flag for our closures function that will formatting page in depend on `canView` permissions.

And then in BrokenLinksReport class in method columns() add formatting for row with records with restrictions.

```php
 'formatting' => function ($value, $item, $flag=false) use ($linkBase) {
                return $flag
                    ? sprintf(
                        '<p class="disabled-record">%s</p>',
                        $value
                    )
                    : sprintf(
                        '<a href="%s" title="%s">%s</a>',
                        Controller::join_links($linkBase, $item->ID),
                        _t(__CLASS__ . '.HoverTitleEditPage', 'Edit page'),
                        $value
                    );
                }
```
 
This solution provides ability to see full list of broken links even if Page requires special permissions. It's good for analytic purpose, but it's not good to make these changes in GridField class itself. 

I'm not sure, that it's expedient, but as a solution it works.  

***Note
To support this approach for "Export to CSV", we also should make changes for generateExportFileData() in GridFieldExportButton class.

**Comment by sabina-talipova** [comment] 2022-04-26 01:09
Probably, accessible solution is show full list of pages with broken links, but for pages with restriction, we won't provide link to the page. So in this case, use will see all pages with broken links, but have access to view or edit page only if he has a permission.

**Comment by maxime-rainville** [comment] 2022-04-27 05:27
Manage to replicate the issue here: https://youtu.be/AZotDQztbB8

I think the problem is here: https://github.com/silverstripe/silverstripe-externallinks/blob/164032af762cbc9eea3308640e5940dfbca9081d/src/Model/BrokenExternalLink.php#L58-L63

The `BrokenExternalLink` DataObject is what gets iterated over in the External Broken Link report.

However, the `'content-authors', 'administrators'` permissions are nonsensical. Permission code should be something like `CMS_ACCESS_CMSMain`. My gut feeling is that it's probably OK to show entries for pages you can't access. The only thing you will see is the title.

Alternatively, we could rewrite `CanView` to call the parent Page's can view method.

**Comment by sabina-talipova** [comment] 2022-04-27 21:00
Oups...
Unfortunately, I've been testing just BrokenLinks not ExternalBrokenLinks.

**Comment by GuySartorelli** [comment] 2022-05-05 21:48
Closing this issue - the PR is merged.

**Closed as completed by GuySartorelli** 2022-05-05 21:48 UTC
Labels: type/bug, affects/v4, complexity/low, impact/high
